photos/urls.py
from django.urls import path
from . import view

app_name = 'photos'

urlpatterns = [
    
    path('index/', view.IndexView.as_view(), name='index'),
    path('<int:num_album>/selecao/', view.selecao, name='selecao'),
    path('<int:slideshow_codigo>/configuracao/', view.configuracao, name='configuracao'),
    path('<int:slideshow_codigo>/slideshow/', view.slideshow, name='slideshow'),
    path('<int:slideshow_codigo>/slideshow/check_progress', view.check_progress, name='check_progress')
]

photos/templates/photos/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <link rel="shortcut icon" href="{% static 'photos/icon/images-solid.ico' %}" type="image/ico">
    <link rel="stylesheet" href="{% static 'photos/css/base.css' %}">
    <title>Photo Slideshow</title>
</head>

<body>
    <header>
        {% include 'photos/base/header.html' %}
    </header>
    <main>
        {% block main %} {% endblock %}
    </main>
    <footer>
        {% include 'photos/base/footer.html' %}
    </footer>

    <script type="text/javascript" src="{% static 'photos/js/jquery.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    {% block scripts %} {% endblock %}
</body>

</html>

photos/templates/photos/base/header.html
<nav id="navbar" class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand font-weight-bold" href="{% url 'photos:index' %}">
        <i id="icone-logo" class="fas fa-images"></i>
        <span>Photo Slideshow</span>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <span class="nav-link">
                {% if user.first_name %}
                    Olá, {{ user.first_name }}
                {% else %}
                    Olá, {{ user.username }}
                {% endif %}
                </span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'usuario:logout' %}">Sair</a>
            </li>

            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'usuario:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'usuario:cadastro' %}">Cadastre-se</a>
            </li>

            {% endif %}
        </ul>
    </div>
</nav>

photos/templates/photos/configuracao.html
{% extends 'photos/base/base.html' %}
{% load static %}

{% block main %}

<div class="container pb-5">

    <!-- Menu de navegação
        =================== -->
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{% url 'photos:index' %}">Álbuns</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'photos:selecao' request.session.slideshow.album.numero %}">Seleção</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Configuração</li>
        </ol>
    </nav>

    <form action="{% url 'photos:slideshow'  request.session.slideshow.codigo %}" method="POST">
        {% csrf_token %}
        <div class="container">

            <!-- Titulo da página
                ================== -->
            <div class="row">

                <div class="col-12 p-2">
                    <h2 class="mt-sm-5 mt-3 titulo-pagina">
                        <i class="fas fa-cogs"></i>
                        Configuração
                    </h2>
                    <p class="text-justify">
                        Selecione as configurações desejadas para o seu slideshow.
                    </p>
                </div>
            </div>

            <!-- Formato do Vídeo
                ================== -->
            <div class="row">

                <div class="col-6 p-2">
                    <div class="card h-100 w-100" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">Formato</h5>
                            {% for formato in formatos %}
                            <div class="custom-control custom-radio custom-control-inline">

                                {% if formato == 'mp4' %}
                                <input checked type="radio" id="fmt_{{forloop.counter}}" name="formato" value="{{formato}}"
                                    class="custom-control-input">
                                {% else %}
                                <input disabled type="radio" id="fmt_{{forloop.counter}}" name="formato" value="{{formato}}"
                                    class="custom-control-input">
                                {% endif %}

                                <label class="custom-control-label" for="fmt_{{forloop.counter}}">{{formato}}</label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <!-- Resolução do Vídeo
                    ====================-->
                <div class="col-6 p-2">
                    
                    <div class="card h-100 w-100" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">Resolução</h5>

                            {% for resolucao in resolucoes %}
                            <div class="custom-control custom-radio custom-control-inline">

                                {% if resolucao == '720p' %}
                                <input checked type="radio" id="res_{{forloop.counter}}" name="resolucao" value="{{resolucao}}"
                                    class="custom-control-input">
                                {% else %}
                                <input type="radio" id="res_{{forloop.counter}}" name="resolucao" value="{{resolucao}}"
                                    class="custom-control-input">
                                {% endif %}

                                <label class="custom-control-label" for="res_{{forloop.counter}}">{{resolucao}}</label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

             <!-- Segundos de exibição de cada imagens
                ====================================== -->
            <div class="row">
                <div class="col-12 p-2">
                    
                    <div class="card h-100 w-100" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">Exibição de Cada Foto</h5>
                            <label for="segundos_foto"><span id="seg_span">5</span> Segundo(s)</label>
                            <input type="range" id="segundos_foto" value="5" name="segundos_foto" class="custom-range"
                                min="1" max="15" step="1">
                        </div>
                    </div>
                    
                </div>
            </div>

            <!-- Progresso Download Imagens
                ============================-->
            <div class="text-center mt-5" >
                <div id="loader-imagens" style="display: none">
                    <div class="loader mx-auto"></div>
                    <p class="mt-3">Fazendo o download das imagens...</p>
                </div>
                <button id="btn-salvar" type="submit" class="btn btn-primary btn-lg w-25" style="min-width: 100px;">Salvar</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'photos/js/configuracao.js'%}"></script>
{% endblock %}

photos/templates/photos/index.html
{% extends 'photos/base/base.html' %}

{% block main %}

<div class="container pb-3">

    <!-- Menu de navegação
        =================== -->
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb breadcrumb bg-light">
            <li class="breadcrumb-item active" aria-current="page"> Álbuns </li>
        </ol>
    </nav>

    <h2 class="mt-sm-5 mt-3 titulo-pagina">
        <i class="far fa-address-book"></i>
        Meus Álbuns
    </h2>
    <p class="text-justify">
        Selecione um álbum para configurar o seu slideshow.
    </p>

    <div class="container mt-sm-5 mt-3">
        <div class="row">
            {% for album in albuns %}
            <div class="col-md-6 mb-3">
                <div class="card h-100">

                    <h5 class="card-header">{{album.title|title}}</h5>

                    <div class="card-body d-flex flex-wrap">
                        <div class="text-center mx-auto">
                            <img src="{{album.coverPhotoBaseUrl}}" class="rounded" style="height: auto; max-width: 220px; max-height: 210px" alt="...">
                        </div>

                        <div class="d-flex flex-column">
                            <p class="card-text font-weight-bold m-3">{{album.mediaItemsCount}}
                                foto{{album.mediaItemsCount|pluralize}}</p>

                            <a class="btn btn-primary m-1" href="{% url 'photos:selecao' forloop.counter %}">
                                <i class="fas fa-play"></i>
                                CRIAR SLIDESHOW
                            </a>

                            <a class="btn btn-secondary m-1" href="{{ album.productUrl }}" target="_blank">
                                <i class="fas fa-external-link-alt"></i>
                                GOOGLE PHOTOS
                            </a>
                        </div>

                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>

</div>


{% endblock %}

photos/templates/photos/selecao.html
{% extends 'photos/base/base.html' %}
{% load static %}

{% block main %}

<div class="container pb-5">

    <!-- Menu de navegação
        =================== -->
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{% url 'photos:index' %}">Álbuns</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Seleção</li>
        </ol>
    </nav>

    <h2 class="mt-sm-5 mt-3 titulo-pagina">
        <i class="far fa-check-square"></i>
        Seleção
    </h2>
    <p class="text-justify">
        Selecione até <strong id="maximo_fotos">{{maximo_fotos}} fotos</strong> para serem adicionadas ao seu slideshow.
    </p>

    <h3 class="mt-sm-5 mt-3 titulo-pagina">
        Álbum {{request.session.slideshow.album.title|title}}
    </h3>

    <form action="{% url 'photos:configuracao' request.session.slideshow.codigo %}" method="POST">
        {% csrf_token %}
        <div class="container mt-sm-5 mt-3">
            <div class="d-flex flex-row-reverse">
                <button id="btn-desmarcar" type="button" class="btn btn-primary btn-sm m-md-2 m-1">DESMARCAR TODAS</button>
                <button id="btn-marcar" type="button" class="btn btn-primary btn-sm m-md-2 m-1">MARCAR MÁXIMO</button>
            </div>

            <div class="row">
                {% for foto in request.session.slideshow.album.fotos %}

                    {% if 'jpeg' in foto.mimeType %}
                    <div class="col-md-6 mb-3"> 

                        <div class="card h-100">
                            <div class="card-body d-flex flex-wrap">

                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="check_{{ forloop.counter }}"
                                        name="{{forloop.counter}}" value="{{foto.id}}">

                                    <label class="custom-control-label" for="check_{{ forloop.counter }}">
                                        <div class="text-center">
                                            <img src="{{foto.baseUrl}}" class="w-75 rounded">
                                        </div>
                                    </label>
                                </div>


                                <div class="d-flex flex-column mt-3">
                                    <p class="card-text  m-1 text-secondary">{{foto.mediaMetadata.width}} x {{foto.mediaMetadata.height}}</p>
                                    <p id="data_criacao_{{forloop.counter}}" class="card-text  m-1 text-secondary">{{foto.mediaMetadata.creationTime }}</p>
                                    <a class="btn btn-secondary btn-sm m-1" href="{{ foto.productUrl }}" target="_blank">
                                        <i class="fas fa-external-link-alt"></i>
                                        GOOGLE PHOTOS
                                    </a>

                                </div>

                            </div>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="text-center mt-5">
                <button id="salvar" type="submit" class="btn btn-primary btn-lg w-25" style="min-width: 100px;">Salvar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'photos/js/selecao.js'%}"></script>
{% endblock %}

photos/templates/photos/slideshow.html
{% extends 'photos/base/base.html' %}
{% load static %}

{% block main %}

<div class="container pb-5">

    <!-- Menu de navegação
        =================== -->
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{% url 'photos:index' %}">Álbuns</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'photos:selecao' request.session.slideshow.album.numero %}">Seleção</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'photos:configuracao' request.session.slideshow.codigo %}">Configuração</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Slideshow</li>
        </ol>
    </nav>
    <div class="container">
        <div class="row">
            <!-- Titulo -->
            <div class="col-12 p-2">
                <h2 class="mt-sm-5 mt-3 titulo-pagina">
                    <i id="icone-logo" class="fas fa-images"></i>
                    Slideshow
                </h2>
                <p id="msg-status" class="text-justify">
                    O seu slideshow está sendo criado...
                </p>
            </div>
        </div>

        <div id="painel-video" style="display: none">
            <div class="embed-responsive embed-responsive-21by9">
                <video controls>
                    <!-- Inserido por javascript: <source> -->
                </video>
            </div>

            <div class="text-center mt-5">
                <a id="btn-download" class="btn btn-primary btn-lg w-25" style="min-width: 130px;" download="slideshow.mp4">Download</a>
            </div>
        </div>

        <div id="painel-progresso" class="row">
            <div class="col-12" style="height: 30vh">
                <div class="progress mt-5 w-75 mx-auto">
                    <div id="progress_video" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                        aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0"></div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'photos/js/slideshow.js'%}?v=1"></script>
{% endblock %}